import AutoRouteRefresh from '../../../components/console/AutoRouteRefresh';
import ConsoleNavLink from '../../../components/ConsoleNavLink';
import ConsoleShell from '../../../components/console/ConsoleShell';
import { listManagerClientDirectory, type AccountDirectoryRow } from '../../../lib/saas/account-directory';
import { listManagerOutputApprovals, listManagerUserSettings, type ManagerOutputApproval, type OutputActivityFilter } from '../../../lib/saas/manager-user-settings';
import { managerOperationsNavItems } from '../../../lib/manager-console/manager-operations-panels';
import { requireRole } from '../../../lib/saas/session';
import { normalizeOutputActivityFilter, outputActivityStatusLabel } from '../../../src/features/manager-output-activity/output-activity-contract';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

type PageProps = { searchParams?: Promise<{ filter?: string | string[]; control?: string | string[]; message?: string | string[] }> };
type OutputActivityCounts = { totalCount: number; perOutputCount: number; fulltimeOutputCount: number; pendingCount: number; approvedCount: number; rejectedCount: number };
function numberText(value: number) { return new Intl.NumberFormat('en-PH', { maximumFractionDigits: 0 }).format(Math.round(value || 0)); }
function first(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] : value; }
function disputerLabel(account?: AccountDirectoryRow, row?: ManagerOutputApproval) { return account?.full_name || account?.email || row?.disputer_id || 'Disputer account'; }
function letterClientLabel(row?: ManagerOutputApproval) { return row?.client_name || 'Letter client not set'; }
function bossInfo(row: ManagerOutputApproval) { return row.notes || 'No note set'; }
function formatPHDateTime(value: string | null | undefined) { if (!value) return 'Generation time not recorded'; try { return new Intl.DateTimeFormat('en-PH', { timeZone: 'Asia/Manila', month: 'short', day: '2-digit', year: 'numeric', hour: 'numeric', minute: '2-digit', hour12: true }).format(new Date(value)); } catch { return 'Generation time not recorded'; } }
function filterHref(filter: OutputActivityFilter) { return filter === 'all' ? '/admin/output-activity-v2' : `/admin/output-activity-v2?filter=${filter}`; }
async function syncRecentGeneratedOutputActivity(supabase: any, managerId: string) { const activitySync = await supabase.rpc('sync_manager_recent_generation_output_activity_v1', { manager_id_input: managerId, max_rows: 50 }); const activityError = activitySync.error?.message || null; const notificationSync = await supabase.rpc('sync_manager_output_activity_notifications_v1', { manager_id_input: managerId, max_rows: 50 }); const notificationError = notificationSync.error?.message || null; return activityError || notificationError; }
function OutputActivityToolbar({ counts }: { counts: OutputActivityCounts }) { const clearableCount = Math.max(0, counts.totalCount - counts.pendingCount); return <section className="output-activity-toolbar" aria-label="Output activity actions"><div className="output-activity-toolbar-copy"><strong>History controls</strong><span>{numberText(clearableCount)} clearable · {numberText(counts.pendingCount)} pending per-output preserved</span></div><form action="/api/manager/output-activity/clear" method="post" className="output-activity-clear-form"><input type="hidden" name="preservePending" value="true" /><button type="submit" className="admin-action-button danger">Clear history</button></form></section>; }
function FilterTabs({ active, counts }: { active: OutputActivityFilter; counts: OutputActivityCounts }) { const tabs: Array<{ value: OutputActivityFilter; label: string; detail: string; count: number }> = [{ value: 'all', label: 'All', detail: 'All generated output', count: counts.totalCount }, { value: 'per_output', label: 'Per output', detail: `${numberText(counts.pendingCount)} pending · ${numberText(counts.approvedCount)} confirmed`, count: counts.perOutputCount }, { value: 'not_per_output', label: 'Fulltime Output', detail: 'No confirmation needed', count: counts.fulltimeOutputCount }]; return <nav className="output-activity-filter-tabs output-activity-count-tabs" aria-label="Output activity filter">{tabs.map((tab) => <ConsoleNavLink key={tab.value} href={filterHref(tab.value)} className={`output-activity-filter-tab ${active === tab.value ? 'active' : ''}`}><span className="output-activity-filter-copy"><strong>{tab.label}</strong><small>{tab.detail}</small></span><b aria-label={`${tab.label} count`}>{numberText(tab.count)}</b></ConsoleNavLink>)}</nav>; }
function DecisionForm({ row, rateAmount }: { row: ManagerOutputApproval; rateAmount: number }) { if (!row.is_per_output) return <span className="output-activity-readonly-note">Fulltime Output</span>; if (row.status === 'pending') return <form action="/api/manager-output-decision" method="post" className="manager-user-settings-form output-decision-form output-decision-form-inline"><input type="hidden" name="activityId" value={row.id} /><label><span>Rate</span><input name="rateAmount" inputMode="decimal" defaultValue={String(Math.round(row.rate_amount || rateAmount || 0))} /></label><button type="submit" name="action" value="confirm" aria-label="Confirm per-output" className="admin-action-button primary">Confirm</button><button type="submit" name="action" value="reject" className="admin-action-button">Return</button></form>; return <span className="output-activity-readonly-note">{outputActivityStatusLabel(row.status, row.is_per_output)}</span>; }
function ActivityRow({ row, account, rateAmount }: { row: ManagerOutputApproval; account?: AccountDirectoryRow; rateAmount: number }) { const isPerOutput = row.is_per_output; const statusLabel = outputActivityStatusLabel(row.status, isPerOutput); const createdAtLabel = formatPHDateTime(row.created_at); return <article className={`output-activity-row output-activity-row-compact ${isPerOutput ? 'payable' : 'recorded'}`} data-output-activity-kind={isPerOutput ? 'per-output' : 'fulltime-output'} data-output-count={row.output_count || 0}><header className="output-activity-card-header"><div className="output-activity-card-main"><div className="output-activity-title-line"><strong>{isPerOutput ? 'Per-output generated letter' : 'Fulltime generated letter'}</strong><div className="output-activity-title-actions"><DecisionForm row={row} rateAmount={rateAmount} /><span className={`admin-status-badge ${isPerOutput ? 'active' : 'pending'}`}>{isPerOutput ? 'Per output' : 'Fulltime Output'}</span></div></div><span className="output-activity-subtitle">{statusLabel} · Generated {createdAtLabel} PH</span><div className="output-activity-meta-line" aria-label="Output activity details"><span><b>Disputer</b>{disputerLabel(account, row)}</span><span><b>Letter client</b>{letterClientLabel(row)}</span><span><b>Boss</b>{bossInfo(row)}</span><span><b>Round</b>{row.round_label || 'Round not set'}</span></div></div></header></article>; }

export default async function ManagerOutputActivityV2Page({ searchParams }: PageProps) {
  const params = searchParams ? await searchParams : {};
  const filter = normalizeOutputActivityFilter(params.filter);
  const controlStatus = first(params.control);
  const controlMessage = first(params.message);
  const { user, profile, supabase } = await requireRole('manager');
  const active = await listManagerClientDirectory(supabase, { view: 'active', page: 1, pageSize: 25 });
  const syncErrorMessage = await syncRecentGeneratedOutputActivity(supabase, user.id);
  const activityResult = await listManagerOutputApprovals(supabase, user.id, [], filter);
  const ids = Array.from(new Set([...active.accounts.map((account) => account.id), ...activityResult.approvals.map((row) => row.disputer_id)].filter(Boolean)));
  const settingsResult = await listManagerUserSettings(supabase, user.id, ids);
  const accountMap = new Map(active.accounts.map((account) => [account.id, account]));
  const counts: OutputActivityCounts = { totalCount: activityResult.totals.totalCount, perOutputCount: activityResult.totals.perOutputCount, fulltimeOutputCount: activityResult.totals.fulltimeOutputCount, pendingCount: activityResult.totals.pendingCount, approvedCount: activityResult.totals.approvedCount, rejectedCount: activityResult.totals.rejectedCount };
  return <ConsoleShell role="manager" mode="operations" email={profile?.email || user.email || 'Manager'} accountLabel="Manager account" brandSubtitle="Manager console" sidebarSectionTitle="Operations" navItems={managerOperationsNavItems('payroll')} switchTarget="/manager-workspace" switchTargetLabel="Manager workspace" navAriaLabel="Manager output activity navigation" activeNavUsesConsoleLink header={{ eyebrow: 'Output Activity', title: 'Generated output.', description: 'Review pending per-output work. Clear history safely while preserving unfinished confirmations.' }}><AutoRouteRefresh /><OutputActivityToolbar counts={counts} />{controlStatus && <section className={`admin-monitor-card admin-feedback-card ${controlStatus === 'ok' ? 'success' : 'error'}`}><strong>{controlStatus === 'ok' ? 'Output activity updated' : 'Output activity error'}</strong><span>{controlMessage || ''}</span></section>}{syncErrorMessage && <section className="admin-monitor-card admin-feedback-card error"><strong>Output notification sync needs database update</strong><span>{syncErrorMessage}</span></section>}{(active.errorMessage || settingsResult.errorMessage || activityResult.errorMessage) && <section className="admin-monitor-card"><div className="admin-monitor-empty">Could not load output activity: {active.errorMessage || settingsResult.errorMessage || activityResult.errorMessage}</div></section>}<FilterTabs active={filter} counts={counts} /><section className="manager-console-stack output-activity-stack">{activityResult.approvals.length ? activityResult.approvals.map((row) => { const account = accountMap.get(row.disputer_id); const setting = settingsResult.settings[row.disputer_id]; return <ActivityRow key={row.id} row={row} account={account} rateAmount={setting?.per_output_rate || setting?.rate || 0} />; }) : <div className="admin-monitor-empty">No generated outputs match this filter.</div>}</section></ConsoleShell>;
}
